# Usando SDK do .NET 9
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

# Define diretório de trabalho
WORKDIR /src
RUN dotnet restore ./tests/OrderManager.Application.Tests/OrderManager.Application.Tests.csproj
RUN dotnet restore ./tests/OrderManager.Infrastructure.Tests/OrderManager.Infrastructure.Tests.csproj
RUN dotnet restore ./tests/OrderManager.Web.Api.Tests/OrderManager.Web.Api.Tests.csproj

# Copia todos os arquivos do projeto para o container
COPY . .

# Restaura dependências
RUN dotnet restore

# Build do projeto sem restore (já feito)
RUN dotnet build --no-restore

# Comando padrão: roda todos os testes
CMD ["dotnet", "test", "--no-build", "--logger:trx"]
