// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManager.Infrastructure.Persistence;

#nullable disable

namespace OrderManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211193021_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManager.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstimatedDeliveryDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("FreightCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("FreightType")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "joao.cwb@email.com",
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CustomerName = "Joao do BV",
                            EstimatedDeliveryDays = 5,
                            FreightCost = 20m,
                            FreightType = 1,
                            PaymentStatus = 0,
                            Status = 0,
                            Total = 200m,
                            UpdatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            xmin = 0u
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "maria.souza@email.com",
                            CustomerId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CustomerName = "Maria Souza",
                            EstimatedDeliveryDays = 3,
                            FreightCost = 15m,
                            FreightType = 1,
                            PaymentStatus = 0,
                            Status = 0,
                            Total = 90m,
                            UpdatedAt = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            xmin = 0u
                        });
                });

            modelBuilder.Entity("OrderManager.Domain.Entities.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Produto A",
                            OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 2,
                            Sku = "SKU-001",
                            UnitPrice = 50m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Produto B",
                            OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 1,
                            Sku = "SKU-002",
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Produto C",
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Quantity = 3,
                            Sku = "SKU-003",
                            UnitPrice = 30m
                        });
                });

            modelBuilder.Entity("OrderManager.Domain.Entities.Orders.Order", b =>
                {
                    b.OwnsOne("OrderManager.Domain.Entities.Orders.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("Number")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasData(
                                new
                                {
                                    OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    Cep = "12345-678",
                                    City = "Curitiba",
                                    Complement = "Apto 101",
                                    Id = new Guid("55555555-5555-5555-5555-555555555555"),
                                    Neighborhood = "Centro",
                                    Number = 100,
                                    State = "PR",
                                    Street = "Rua das Flores"
                                },
                                new
                                {
                                    OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                                    Cep = "98765-432",
                                    City = "Curitiba",
                                    Complement = "",
                                    Id = new Guid("66666666-6666-6666-6666-666666666666"),
                                    Neighborhood = "Jardins",
                                    Number = 100,
                                    State = "PR",
                                    Street = "Avenida Brasil"
                                });
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderManager.Domain.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("OrderManager.Domain.Entities.Orders.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManager.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
